### ISSUE TITLE
”select test.* from test“查询语句执行异常

### ISSUE THREAD

**Issue by notNNORTH** [notNNORTH/TMDB#4]
tmdb> select * from test;
|test.id             |test.value1         |test.value2         |
|1                   |10                  |100                 |
|2                   |1                   |2                   |
|3                   |1                   |2                   |
|4                   |1                   |2                   |
tmdb> select test.* from test;
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at edu.whu.tmdb.query.operations.impl.SelectImpl.elicit(SelectImpl.java:363)
	at edu.whu.tmdb.query.operations.impl.SelectImpl.plainSelect(SelectImpl.java:97)
	at edu.whu.tmdb.query.operations.impl.SelectImpl.select(SelectImpl.java:63)
	at edu.whu.tmdb.query.Transaction.query(Transaction.java:167)
	at edu.whu.tmdb.Main.execute(Main.java:74)
	at edu.whu.tmdb.Main.main(Main.java:34)

执行select test.* from test语句时期待返回查询结果，系统实际上报错终止

**Comment by notNNORTH** [comment]
经排查问题出现在初始创建projectResult时其大小初始化为selectItem的大小，当出现select test.* from test;这样的语句时，判断selectItem大小为1，而要求的projectResult为test的全部元组。因此出现非法访问
