### ISSUE TITLE
select查询中where字句不支持负数表达式

### ISSUE THREAD

**Issue by notNNORTH** [notNNORTH/TMDB#5]
tmdb> select * from test2 where test2.value2<-1;
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at edu.whu.tmdb.query.operations.impl.Where.minorThan(Where.java:265)
	at edu.whu.tmdb.query.operations.impl.Where.execute(Where.java:71)
	at edu.whu.tmdb.query.operations.impl.Where.where(Where.java:45)
	at edu.whu.tmdb.query.operations.impl.SelectImpl.plainSelect(SelectImpl.java:86)
	at edu.whu.tmdb.query.operations.impl.SelectImpl.select(SelectImpl.java:63)
	at edu.whu.tmdb.query.Transaction.query(Transaction.java:167)
	at edu.whu.tmdb.Main.execute(Main.java:74)
	at edu.whu.tmdb.Main.main(Main.java:34)

**Comment by notNNORTH** [comment]
Formula.java文件中不存在对负数（SignedExpression类型）的case判断，因此返回空数值列表
已加入相关判断逻辑
