### ISSUE TITLE
数据库不支持删除表中所有元组的sql语句

### ISSUE THREAD

**Issue by notNNORTH** [notNNORTH/TMDB#6]
tmdb> delete from table1;
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "Object.toString()" because "where" is null
	at edu.whu.tmdb.query.operations.impl.DeleteImpl.execute(DeleteImpl.java:40)
	at edu.whu.tmdb.query.operations.impl.DeleteImpl.delete(DeleteImpl.java:33)
	at edu.whu.tmdb.query.Transaction.query(Transaction.java:163)
	at edu.whu.tmdb.Main.execute(Main.java:71)
	at edu.whu.tmdb.Main.main(Main.java:31)

**Comment by notNNORTH** [comment]
源代码中忽视where字句为null的条件判断，补齐后修正结果
